language: node_js
services:
  - redis-server
node_js:
- "10"
cache:
  directories:
  - "node_modules"

stages:
- name: update-deps
  if: (branch = master) AND (type = cron)
- name: test
  if: (type != cron)
- name: deploy-npm
  if: (tag =~ ^v)

jobs:
  include:
  - stage: update-deps
    name: Update package dependencies
    script:
    - npm run update-dep
    - npm test
  - stage: test
    name: Test
    script:
    - npm test
  - stage: deploy-npm
    name: Deploy to npm
    deploy:
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      skip_cleanup: true
      on:
        tags: true
